//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BromoAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class KodePromo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KodePromo()
        {
            this.TransaksiHeaders = new HashSet<TransaksiHeader>();
        }
    
        public int ID { get; set; }
        public string Kode { get; set; }
        public int PersentaseDiskon { get; set; }
        public int MaksimumDiskon { get; set; }
        public System.DateTime BerlakuSampai { get; set; }
        public string Deskripsi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaksiHeader> TransaksiHeaders { get; set; }
    }
}
