//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BromoAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerubahanStatusJadwalPenerbangan
    {
        public int ID { get; set; }
        public int JadwalPenerbanganID { get; set; }
        public int StatusPenerbanganID { get; set; }
        public System.TimeSpan WaktuPerubahanTerjadi { get; set; }
        public System.TimeSpan PerkiraanWaktuDelay { get; set; }
    
        public virtual JadwalPenerbangan JadwalPenerbangan { get; set; }
        public virtual StatusPenerbangan StatusPenerbangan { get; set; }
    }
}
